
#include "globals.h"
#include "space.h"
#include "misc.h"
#include "mpl.h"
#include "x86.h"

#ifndef _DEMO




///////////////////////////////////////////////////////////

#define	OP_REL		MAKEOPC(OPC_ADDRESS|OPC_GLOBAL)|MAKEOPTYP(OPTYP_PTR32)
#define	OP_I2		MAKEOPC(OPC_IMM)|MAKEOPSZ(OPSZ_WORD)
#define	OP_PM(t)	MAKEOPC(OPC_ADDRESS|OPC_GLOBAL)|MAKEOPTYP(OPTYP_PTR32)|MAKEOPTYPX(t)
#define	OP_PMX(t)	MAKEOPC(OPC_GLOBAL)|MAKEOPTYP(OPTYP_PTR32)|MAKEOPTYPX(t)

//1:BYTE(1,U)
//2:BOOLEAN(1)
//3:WORD(2,U)
//4:INTEGER(2,S)
//5:LONGINT(4,S)
//6:STRING(256)
//7:FLOAT(4)
//8:TIMEFLOAT(8)
//9:LONGWORD(4,U)

#define __SP(arg)		(((arg*OPSZ_DWORD)&0xFFFF)<<16)

///////////////////////////////////////////////////////////

// A S S I G N C S
IT_FRM(ASSIGNCS)
IT_BEG(ASSIGNCS)
	ACTN1(ACTN_ASSIGNCS)
		ACTN1(ACTN_NULL)
IT_END(ASSIGNCS)

// A S S I G N D S
IT_FRM(ASSIGNDS)
IT_BEG(ASSIGNDS)
	ACTN1(ACTN_ASSIGNDS)
		ACTN1(ACTN_NULL)
IT_END(ASSIGNDS)

// C A L L
IT_FRM(CALL)
	{OP_PM(0)},
IT_BEG(CALL)
	ACTN1(ACTN_CALL)
		OPND1(OPND_1)
		ACTN1(ACTN_NULL)
IT_END(CALL)

// D A S S I G N
IT_FRM(DASSIGN)
	{OP_I2,	OP_PM(0)},
IT_BEG(DASSIGN)
	ACTN1(ACTN_DASSIGN)
		ACTN1(ACTN_COMMA0)
			OPND1(OPND_1)
			OPND1(OPND_2)
IT_END(DASSIGN)

// D C L O S E
IT_FRM(DCLOSE)
	{OP_I2},
IT_BEG(DCLOSE)
	ACTN1(ACTN_DCLOSE)
		OPND1(OPND_1)
IT_END(DCLOSE)

// D C O M M A N D
IT_FRM(DCOMMAND)
	{OP_I2,	OP_PM(0),	OP_I2},
IT_BEG(DCOMMAND)
	ACTN1(ACTN_DCOMMAND)
		ACTN1(ACTN_COMMA0)
			OPND1(OPND_1)
			ACTN1(ACTN_COMMA0)
				OPND1(OPND_2)
				OPND1(OPND_3)
IT_END(DCOMMAND)

// D E R R O R
IT_FRM(DERROR)
	{OP_I2,	OP_PM(OPSZ_WORD)},
IT_BEG(DERROR)
	ACTN1(ACTN_MOV)
		ACTN1(ACTN_INDIR)
			OPND1(OPND_2)
		ACTN1(ACTN_DERROR)
			OPND1(OPND_1)
IT_END(DERROR)

// D O N E R R O R		//assotiate the device with ON-error handle
IT_FRM(DONERROR)
	{OP_I2,	OP_PM(0)},
IT_BEG(DONERROR)
	ACTN1(ACTN_DONERROR)
		ACTN1(ACTN_COMMA0)
			OPND1(OPND_1)
			OPND1(OPND_2)
IT_END(DONERROR)

// D R E S U L T
IT_FRM(DRESULT)
	{OP_I2,	OP_PM(0),	OP_I2},
IT_BEG(DRESULT)
	ACTN1(ACTN_DRESULT)
		ACTN1(ACTN_COMMA0)
			OPND1(OPND_1)
			ACTN1(ACTN_COMMA0)
				OPND1(OPND_2)
				OPND1(OPND_3)
IT_END(DRESULT)

// D S E E K
IT_FRM(DSEEK)
	{OP_I2,	OP_PM(OPSZ_DWORD),	OP_PM(OPSZ_DWORD)},
IT_BEG(DSEEK)
	ACTN1(ACTN_DSEEK)
		ACTN1(ACTN_COMMA0)
			OPND1(OPND_1)
			ACTN1(ACTN_COMMA0)
				ACTN1(ACTN_INDIR)
					OPND1(OPND_2)
				ACTN1(ACTN_INDIR)
					OPND1(OPND_3)
IT_END(DSEEK)

// D W R I T E
IT_FRM(DWRITE)
	{OP_I2,	OP_PM(0),	OP_I2},
IT_BEG(DWRITE)
	ACTN1(ACTN_DWRITE)
		ACTN1(ACTN_COMMA0)
			OPND1(OPND_1)
			ACTN1(ACTN_COMMA0)
				OPND1(OPND_2)
				OPND1(OPND_3)
IT_END(DWRITE)

// J M P
IT_FRM(JMP)
	{OP_REL},
IT_BEG(JMP)
	ACTN1(ACTN_GOTO)
		OPND1(OPND_1)
IT_END(JMP)

// L O A D B P
IT_FRM(LOADBP)
	{OP_PM(0)},
IT_BEG(LOADBP)
	ACTN4(ACTN_MOV, 0, __SP(-1))
		OPND3(OPC_INDIRECT|SSID_STACKPTR, OPSZ_DWORD, 0)
		OPND1(OPND_1)
IT_END(LOADBP)

// M A D D S
IT_FRM(MADDS)		//Concatenate 2 strings into 3rd
	{OP_PM(0),	OP_PM(0),	OP_PM(0)},
IT_BEG(MADDS)
	ACTN1(ACTN_MADDS)
		ACTN1(ACTN_COMMA0)
			OPND1(OPND_1)
			ACTN1(ACTN_COMMA0)
				OPND1(OPND_2)
				OPND1(OPND_3)
IT_END(MADDS)

// M B O U N D S
IT_FRM(MBOUNDS)
	{OP_PM(OPSZ_DWORD),	OP_I2,	OP_I2},
IT_BEG(MBOUNDS)
	ACTN1(ACTN_MBOUNDS)
		ACTN1(ACTN_COMMA0)
			ACTN1(ACTN_INDIR)
				OPND1(OPND_1)
			ACTN1(ACTN_COMMA0)
				OPND1(OPND_2)
				OPND1(OPND_3)
IT_END(MBOUNDS)

// M D A D A 1		//Copy BYTE (1 bytes)
IT_FRM(MDADA1)
	{OP_PM(OPSZ_BYTE),	OP_PM(OPSZ_BYTE)},
IT_BEG(MDADA1)
// OP2:1 = OP1:1
	ACTN1(ACTN_MOV)
		ACTN1(ACTN_INDIR)
			OPND1(OPND_2)
		ACTN1(ACTN_INDIR)
			OPND1(OPND_1)
IT_END(MDADA1)

// M D A D A 3		//Copy DWORD (4 bytes)
IT_FRM(MDADA3)
	{OP_PM(OPSZ_DWORD),	OP_PM(OPSZ_DWORD)},
IT_BEG(MDADA3)
	ACTN1(ACTN_MOV)
		ACTN1(ACTN_INDIR)
			OPND1(OPND_2)
		ACTN1(ACTN_INDIR)
			OPND1(OPND_1)
IT_END(MDADA3)

// M D A D A 4		//Copy string
IT_FRM(MDADA4)
	{OP_PM(0),	OP_PM(0)},
IT_BEG(MDADA4)
	ACTN1(ACTN_MDADA4)
		ACTN1(ACTN_COMMA0)
			OPND1(OPND_1)
			OPND1(OPND_2)
IT_END(MDADA4)

// M D A D A 7		//Copy QWORD (8 bytes)
IT_FRM(MDADA7)
	{OP_PM(OPSZ_QWORD),	OP_PM(OPSZ_QWORD)},
IT_BEG(MDADA7)
	ACTN1(ACTN_MOV)
		ACTN1(ACTN_INDIR)
			OPND1(OPND_2)
		ACTN1(ACTN_INDIR)
			OPND1(OPND_1)
IT_END(MDADA7)

// M I T O A
IT_FRM(MITOA)
	{OP_PM(OPSZ_WORD),	OP_PM(0)},
IT_BEG(MITOA)
	ACTN1(ACTN_MITOA)
		ACTN1(ACTN_COMMA0)
			ACTN1(ACTN_INDIR)
				OPND1(OPND_1)
			OPND1(OPND_2)
IT_END(MITOA)

// M L E N G T H
IT_FRM(MLENGTH)
	{OP_PM(0),	OP_PM(OPSZ_WORD)},
IT_BEG(MLENGTH)
	ACTN1(ACTN_MOV)
		ACTN1(ACTN_INDIR)
			OPND1(OPND_2)
		ACTN1(ACTN_MLENGTH)
			OPND1(OPND_1)
IT_END(MLENGTH)

// M O D U L E
IT_FRM(MODULE)
	{OP_PM(0)},
IT_BEG(MODULE)
	ACTN1(ACTN_MODULE)
		OPND1(OPND_1)
IT_END(MODULE)

// M O N		//associate the CENTER var with ON-handle
IT_FRM(MON)
	{OP_PM(0),	OP_PM(0)},
IT_BEG(MON)
	ACTN1(ACTN_MON)
		ACTN1(ACTN_COMMA0)
			OPND1(OPND_1)
			OPND1(OPND_2)
IT_END(MON)

// M S Y N C
IT_FRM(MSYNC)
IT_BEG(MSYNC)
	ACTN1(ACTN_MSYNC)
		ACTN1(ACTN_NULL)
IT_END(MSYNC)

// M T C B F
IT_FRM(MTCBF)	//Convert BYTE to FLOAT
	{OP_PM(OPTYP_UCHAR),	OP_PM(OPTYP_FLOAT)},
IT_BEG(MTCBF)
	ACTN1(ACTN_MOV)
		ACTN1(ACTN_INDIR)
			OPND1(OPND_2)
			ACTN1(ACTN_INDIR)
				OPND1(OPND_1)
IT_END(MTCBF)

// M T C B I	//SignExtend BYTE to INTEGER
IT_FRM(MTCBI)
	{OP_PM(OPTYP_UCHAR),	OP_PM(OPTYP_SHORT)},
IT_BEG(MTCBI)
	ACTN1(ACTN_MOV)
		ACTN1(ACTN_INDIR)
			OPND1(OPND_2)
		ACTN1(ACTN_SIGNEXT)
			ACTN1(ACTN_INDIR)
				OPND1(OPND_1)
IT_END(MTCBI)

// M T C B L	//SignExtend BYTE to LONGINT
IT_FRM(MTCBL)
	{OP_PM(OPTYP_UCHAR),	OP_PM(OPTYP_LONG)},
IT_BEG(MTCBL)
	ACTN1(ACTN_MOV)
		ACTN1(ACTN_INDIR)
			OPND1(OPND_2)
		ACTN1(ACTN_SIGNEXT)
			ACTN1(ACTN_INDIR)
				OPND1(OPND_1)
IT_END(MTCBL)

// M T C B W	//ZeroExtend BYTE to WORD
IT_FRM(MTCBW)
	{OP_PM(OPTYP_UCHAR),	OP_PM(OPTYP_USHORT)},
IT_BEG(MTCBW)
	ACTN1(ACTN_MOV)
		ACTN1(ACTN_INDIR)
			OPND1(OPND_2)
		ACTN1(ACTN_ZEROEXT)
			ACTN1(ACTN_INDIR)
				OPND1(OPND_1)
IT_END(MTCBW)

// M T C B X	//ZeroExtend BYTE to LONGWORD
IT_FRM(MTCBX)
	{OP_PM(OPTYP_UCHAR),	OP_PM(OPTYP_ULONG)},//memory address of type <>
	{OP_PM(OPTYP_UCHAR),	OP_PMX(OPTYP_ULONG)},//ptr to memory of type <>
IT_BEG(MTCBX)
	ACTN1(ACTN_MOV)
		ACTN1(ACTN_INDIR)
			OPND1(OPND_2)
		ACTN1(ACTN_ZEROEXT)
			ACTN1(ACTN_INDIR)
				OPND1(OPND_1)
IT_END(MTCBX)

// M T C W X
IT_FRM(MTCWX)	//ZeroExtend WORD to LONGWORD
	{OP_PM(OPTYP_USHORT),	OP_PM(OPTYP_ULONG)},
IT_BEG(MTCWX)
	ACTN1(ACTN_MOV)
		ACTN1(ACTN_INDIR)
			OPND1(OPND_2)
		ACTN1(ACTN_ZEROEXT)
			ACTN1(ACTN_INDIR)
				OPND1(OPND_1)
IT_END(MTCWX)

// M Z V A R U S E
IT_FRM(MZVARUSE)
	{OP_PM(0),	OP_PM(0),	OP_I2},
IT_BEG(MZVARUSE)
	ACTN1(ACTN_MZVARUSE)
		ACTN1(ACTN_COMMA0)
			OPND1(OPND_1)
			ACTN1(ACTN_COMMA0)
				OPND1(OPND_2)
				OPND1(OPND_3)
IT_END(MZVARUSE)

// M Z V A R W R I T E
IT_FRM(MZVARWRITE)
	{OP_PM(0)},
IT_BEG(MZVARWRITE)
	ACTN1(ACTN_MZVARWRITE)
		OPND1(OPND_1)
IT_END(MZVARWRITE)

// R E T
IT_FRM(RET)
IT_BEG(RET)
	ACTN4(ACTN_RET, 0, __SP(1))
		OPND4(OPC_ADDRESS|OPC_GLOBAL, 0, 0, "@RETPATH")
//		OPND3(OPC_IMM, OPSZ_WORD, 0)
IT_END(RET)

// W R I T E P T R
IT_FRM(WRITEPTR)
	{OP_PM(OPSZ_DWORD)},
IT_BEG(WRITEPTR)
	ACTN4(ACTN_MOV, 0, __SP(1))
		ACTN1(ACTN_INDIR)
			OPND1(OPND_1)
		OPND3(OPC_INDIRECT|SSID_STACKPTR, OPSZ_DWORD, 0)
IT_END(WRITEPTR)

////////////////////

//BCONST	OP_I1
//LCONST	OP_I4
//BLANK1
//BLANK2
//BLANK4
//BLANK8
//BLANK256
////////////////////////////////////////////////////////
#endif//_DEMO

static Int8 stackptr_id2offs(UInt8 sz, UInt8 id)
{
	assert((Int8)id >= 0);
	return id;
}

static char *stackptr2str(int sz, int ofs, int flags)
{
	assert(sz == OPSZ_DWORD && ofs == 0);
	return "@STACKPTR";
}

static int getstackptr(int &sz, int &ofs, int b)
{
	sz = OPSZ_DWORD;
	ofs = 0;
	return 1;
}

int FRONTEND_MPL_t::Setup()
{
	FRONTEND_t::Setup();

	m_flags = FE_MPL;
	m_name = "Peus MPL";

	AddStorage(SSID_STACKPTR, STORAGE_t("STACKPTR", SS_REGISTER, 
		stackptr_id2offs, 0, stackptr2str, getstackptr));

#ifndef _DEMO
	m_ITS[0] = outMPL_t::g_list;
#endif

	m_ptr_near = OPSZ_DWORD;
	m_ptr_far = -1;

	static r_t stack_ptr[] = {
		{SSID_STACKPTR, 0 , OPSZ_DWORD},
	};
	m_stack_ptr = &stack_ptr[0];
/*
	static const r_t stackb_ptr = 
		{OPC_CPUREG,OFS(R_BP),SIZ(R_BP)};
	fe.stackb_ptr = stackb_ptr;

	static r_t sav_regs[] = {
		{OPC_CPUREG, OFS(R_AX), SIZ(R_AX)},
		{OPC_CPUREG, OFS(R_CX), SIZ(R_CX)},
		{OPC_CPUREG, OFS(R_DX), SIZ(R_DX)},
		{OPC_CPUREG, OFS(R_BX), SIZ(R_BX)},
		{OPC_CPUREG, OFS(R_SP), SIZ(R_SP)},//will be skipped
		{OPC_CPUREG, OFS(R_BP), SIZ(R_BP)},
		{OPC_CPUREG, OFS(R_SI), SIZ(R_SI)},
		{OPC_CPUREG, OFS(R_DI), SIZ(R_DI)},
		{0,0,0}};
	fe.sav_regs = sav_regs;
	fe.sav_regs_def = 0xFC00;//bp,si,di
	fe.sav_flags_def = 0;//CPUSW_MASK;
*/
	m_stackaddrsz = OPSZ_BYTE;

/*	static char *fdefs[] = {
		"ASSIGNCS",		"0 0 0 0 0 ffffffff 0 0ffff",
		"ASSIGNDS",		"0 0 0 0 0 ffffffff 0 0ffff",
		"DERROR",		"0 0 0 0 0 ffffffff 0 0ffff",
		0};

	fe.fdefs = fdefs;*/
	m_fdef0 = "0";

	return 1;
}


