#pragma once


#include "front_IA.h"


#define __R8(arg)	MAKEOPC(OPC_CPUREG)|MAKEOPSZ(OPSZ_BYTE)|MAKEOPID(OFS(arg))
#define __R16(arg)	MAKEOPC(OPC_CPUREG)|MAKEOPSZ(OPSZ_WORD)|MAKEOPID(OFS(arg))
#define __R32(arg)	MAKEOPC(OPC_CPUREG)|MAKEOPSZ(OPSZ_DWORD)|MAKEOPID(OFS(arg))
#define __R64(arg)	MAKEOPC(OPC_CPUREG)|MAKEOPSZ(OPSZ_QWORD)|MAKEOPID(OFS(arg))


enum CPURegs8_t : unsigned {//r8
	OP_R8 = __R8(-1),//all/undefined
	R8_AL = __R8(R_AL),
	R8_CL = __R8(R_CL),
	R8_DL = __R8(R_DL), 
	R8_BL = __R8(R_BL), 
	R8_AH = __R8(R_AH), 
	R8_CH = __R8(R_CH), 
	R8_DH = __R8(R_DH), 
	R8_BH = __R8(R_BH)};

enum CPURegs16_t : unsigned {//r16
	OP_R16 = __R16(-1),//all
	R16_AX = __R16(R_AX),
	R16_CX = __R16(R_CX),
	R16_DX = __R16(R_DX),
	R16_BX = __R16(R_BX),
	R16_SP = __R16(R_SP),
	R16_BP = __R16(R_BP),
	R16_SI = __R16(R_SI),
	R16_DI = __R16(R_DI)};

enum CPUReg32_t : unsigned {//r32
	OP_R32 = __R32(-1),//all
	R32_EAX = __R32(R_EAX),
	R32_ECX = __R32(R_ECX),  
	R32_EDX = __R32(R_EDX),  
	R32_EBX = __R32(R_EBX),  
	R32_ESP = __R32(R_ESP),  
	R32_EBP = __R32(R_EBP),  
	R32_ESI = __R32(R_ESI),  
	R32_EDI = __R32(R_EDI)};

enum CPUReg64_t : unsigned {//r64
	OP_R64 = __R64(-1),//all
	R64_RAX = __R64(R_RAX),
	R64_RCX = __R64(R_RCX),  
	R64_RDX = __R64(R_RDX),  
	R64_RBX = __R64(R_RBX),  
	R64_RSP = __R64(R_RSP),  
	R64_RBP = __R64(R_RBP),  
	R64_RSI = __R64(R_RSI),  
	R64_RDI = __R64(R_RDI),
	R64_R8 = __R64(R_R8),
	R64_R9 = __R64(R_R9),
	R64_R10 = __R64(R_R10),
	R64_R11 = __R64(R_R11),
	R64_R12 = __R64(R_R12),
	R64_R13 = __R64(R_R13),
	R64_R14 = __R64(R_R14),
	R64_R15 = __R64(R_R15),
	R64_RIP = __R64(R_RIP)
};



#define __SREG(arg)	MAKEOPC(OPC_SEGREG)|MAKEOPSZ(OPSZ_WORD)|MAKEOPID(OFS(arg))
enum SegReg_t : unsigned { 
	OP_SREG = __SREG(-1),//all
	SREG_CS = __SREG(R_CS),
	SREG_DS = __SREG(R_DS),
	SREG_ES = __SREG(R_ES),
	SREG_SS = __SREG(R_SS),
	SREG_FS = __SREG(R_FS),
	SREG_GS = __SREG(R_GS)};

//enum InDirs_t {
	//RM_UNDEFINED = __NDIR(OPSZ_NULL),
	//OP_RM8	= MAKEOPC(OPC_IN DIRECT)|MAKEOPTYP(OPSZ_BYTE),	//r/m8
	//OP_RM16 = MAKEOPC(OPC_IN DIRECT)|MAKEOPTYP(OPSZ_WORD),	//r/m16
	//OP_RM32 = MAKEOPC(OPC_IN DIRECT)|MAKEOPTYP(OPSZ_DWORD),	//r/m32
	//OP_RM64 = MAKEOPC(OPC_I NDIRECT)|MAKEOPTYP(OPSZ_QWORD)};

enum Imms_t {
	OP_IMM		= MAKEOPC(OPC_IMM),
	OP_I8		= OP_IMM|MAKEOPSZ(OPSZ_BYTE),	//imm8
	OP_I16		= OP_IMM|MAKEOPSZ(OPSZ_WORD),	//imm16
	OP_I32		= OP_IMM|MAKEOPSZ(OPSZ_DWORD),	//imm32
	OP_I64		= OP_IMM|MAKEOPSZ(OPSZ_QWORD),	//imm64

//	OP_CF0		= OP_I16|(MAKEOPID(OPID_CF0)),//CF clear
//	OP_CF1		= OP_I16|(MAKEOPID(OPID_CF1)),//CF set

	OP_0		= OP_IMM|(MAKEOPID(OPID_0)),	//0
	OP_1		= OP_IMM|(MAKEOPID(OPID_1)),	//1

	OP_FPUCONST	= OP_IMM|MAKEOPTYP(OPTYP_REAL64),	//special cases
	OP_0R64		= OP_FPUCONST|(MAKEOPID(OPID_0R64)),
	OP_1R64		= OP_FPUCONST|(MAKEOPID(OPID_1R64)),
	OP_L2T		= OP_FPUCONST|(MAKEOPID(OPID_L2T)),
	OP_L2E		= OP_FPUCONST|(MAKEOPID(OPID_L2E)),
	OP_PI		= OP_FPUCONST|(MAKEOPID(OPID_PI)),//pi
	OP_LG2		= OP_FPUCONST|(MAKEOPID(OPID_LG2)),
	OP_LN2		= OP_FPUCONST|(MAKEOPID(OPID_LN2))
	};


enum Rel_t {
	OP_REL8 = MAKEOPC(OPC_ADDRESS|OPC_GLOBAL),		//rel8
	OP_REL16 = MAKEOPC(OPC_ADDRESS|OPC_GLOBAL),		//rel16
	OP_REL32 = MAKEOPC(OPC_ADDRESS|OPC_GLOBAL)		//rel32
	};


//OPC_INDIRECT

enum Mem_t {
	OP_M2BYTE	= MAKEOPC(OPC_DS) | MAKEOPSZ(OPSZ_WORD),
	OP_M8		= MAKEOPC(OPC_DS) | MAKEOPSZ(OPSZ_BYTE),
	OP_M16		= MAKEOPC(OPC_DS) | MAKEOPSZ(OPSZ_WORD),
	OP_M32		= MAKEOPC(OPC_DS) | MAKEOPSZ(OPSZ_DWORD),
	OP_M64		= MAKEOPC(OPC_DS) | MAKEOPSZ(OPSZ_QWORD),
	OP_M32REAL	= MAKEOPC(OPC_DS) | MAKEOPTYP(OPTYP_REAL32),	//m32real
	OP_M64REAL	= MAKEOPC(OPC_DS) | MAKEOPTYP(OPTYP_REAL64),//m64real
	OP_M80REAL	= MAKEOPC(OPC_DS) | MAKEOPTYP(OPTYP_REAL80),	//m80dec
	OP_M16INT	= MAKEOPC(OPC_DS) | MAKEOPTYP(OPTYP_INT16),	//m16int
	OP_M32INT	= MAKEOPC(OPC_DS) | MAKEOPTYP(OPTYP_INT32),	//m32int
	OP_M64INT	= MAKEOPC(OPC_DS) | MAKEOPTYP(OPTYP_INT64),	//m64int
	OP_M80DEC	= MAKEOPC(OPC_DS) | MAKEOPTYP(OPTYP_BCD80),	//m80dec
	OP_M1616	= MAKEOPC(OPC_DS) | MAKEOPTYP(OPTYP_PTR16_FAR),	//m16:16
	OP_M1632	= MAKEOPC(OPC_DS) | MAKEOPTYP(OPTYP_PTR32_FAR),	//m16:32
	OP_M1664	= MAKEOPC(OPC_DS) | MAKEOPTYP(OPTYP_PTR64_FAR),	//m16:64
	};

enum Mem2_t {//memory data
	OP_MOFFS8 = 0,		//moffs8
	OP_MOFFS16 = 0,		//moffs16
	OP_MOFFS32 = 0,		//moffs32
	OP_PTR1616 = 0,//? MAKEOPC(OPC_IMM) | MAKEOPTYP(OPTYP_PTR16_FAR),		//ptr16:16
	OP_PTR1632 = 0	//ptr16:32
	};




	

